### ISSUE TITLE
Golemagg

### ISSUE THREAD

**Issue by Mirakoli123** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1068]
Hey Leute, sagt mal ist das normal das die Kernhund Adds bei Golemagg die Fähigkeit haben zu parieren?

Is mir letztens im MC Raid aufgefallen als ich die Adds getankt habe und eigentlich sollte das doch nicht möglich sein.

Danke

**Comment by dagochen** [comment]
Ich hab zwar auch sowas im Kopf, dass Beasts nicht parieren können, aber ob das damals so war oder ob ich das aus neueren Versionen habe....ka....hast du vielleicht Quellen? Ich hab keine gefunden :(

**Comment by Mirakoli123** [comment]
Ne, hab ich nicht. Klingt für mich aber sowas von unlogisch... Seit wann
können Tiere denn in WoW Parieren?

Am 22. September 2015 um 01:35 schrieb dagochen <notifications@github.com>:

**Comment by Haudraufinix** [comment]
Also es kann auch cirka jeder Mob Blocken, selbst wenn es Zauberkundige ohne Schilde etc sind, könnte mir vorstellen, das da mehr als nur Biester die Parrieren falsch sind

**Comment by Mirakoli123** [comment]
ja, mir ists halt letztens aufgefallen, aber ne Quelle zu finden ist halt
nach 10 Jahren ein bisschen schwer, nich wahr. :)

Am 22. September 2015 um 11:58 schrieb Haudraufinix <
notifications@github.com>:

**Comment by Testear** [comment]
http://vanilla-wow.wikia.com/wiki/Block
Note too, that unlike player characters, mobs sometimes block attacks even though they have no shield equipped. 

http://wowwiki.wikia.com/wiki/Patch_1.3.0
All creatures will now report a Parry on attacks from the front instead of translating them into a 
"Miss." Creatures will no longer be able to Parry attacks from behind. 

http://vanilla-wow.wikia.com/wiki/Parry
Attacks from the rear cannot be parried. Mobs sometimes do so anyways - this can be due to a bug or because they turn very quickly in place. 

http://wow.gamepedia.com/Block

Alle NPCs können blocken. Egal ob sie ein Schild haben oder nicht. Parieren sollten, meiner Meinung nach, auch alle NPCs können.

**Comment by dagochen** [comment]
Der parry-Teil von @Testear  ist halt für alle Mobs, nicht nur für Beasts, aber woher hab ich das nur....trügt das Gedächtnis da so sehr?!

**Comment by nightblizard** [comment]
Ist kein Bug.
