### ISSUE TITLE
Exploit in der Warsong: Zaun über Tunnel AllyBasis

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1621]
Im Battleground der Warsongschlucht gibt es einen Exploit innerhalb der AlliiertenBasis, den Fank (name von d. Red. geändert) bspw. fleißig nutzen.

Der Zaun direkt oberhalb des Tunnels innerhalb der AlliiertenBasis ist einerseits durch normales Springen zu überwinden sowie besonders leicht für Druiden in Reisegestalt einfach zu durchlaufen, um so den Verfolgern zu entgehen. Dadurch erhalten die Alliierten einen klaren Vorteil beim Zurückbringen der Flagge...

Ich bitte daher, dies zu berichtigen.

beste Grüße

Frost

**Comment by Rukachi** [comment]
1. Vorlage benutzen
2. Kein Namecalling
3. Bei euch gibt es auch reichlich dudus die sich mit Noggenfogger einen weg vom Healhaus zu eurem Fh verschaffen.

**Comment by hraesvelgr** [comment]
4. quellen zeigen dass dies nicht so war.

**Comment by testear** [comment]
Die Quellen, dass das so war oder nicht so war gehören zum Bugreport.

Btw ist es normal sich erstmal an der eigenen Nase zu packen, da die Horde schon immer (ist ja auch Blizzlike) die Möglichkeit hat über den Zaun zu früh ins Spiel zu springen. 

https://www.youtube.com/watch?v=6S8puOdQlvE

Wenn sowas möglich ist soll es nicht möglich sein durch den Zaun überm Allitunnel zu latschen an der richtigen Stelle? Bullshit wenn du mich fragst.

**Comment by Seniorash** [comment]
Wie beweist man denn etwas, was es nicht gegeben hat?

**Comment by ChichiWarrior** [comment]
@Frostlatte: Bitte verbessere einen Report und halte dich an die Vorlage, macht es einfacher und übersichtlicher.

Hört auf mit Fingern auf andere zu zeigen. Unschuldig ist keine Fraktion.

Haben mehrere Leute Zugriff auf den Account testear?

Mal sind deine Kommentare echt zu gebrauchen, aber in letzter Zeit ist das sehr traurig was man von dir lesen muss.

Der besagte Spieler hatte, wie man von mehreren Quellen so hört, nicht das erste Mal wegen solchen Aktionen einen Char durch einen Ban verloren.

Was damals funktionierte, braucht nicht zwangsläufig auch hier möglich sein.

Gruß Chichi

**Comment by Badorr** [comment]
@testear 
Wenn es blizzlike war, dass man über den Zaun springen konnte, dafür aber Drei-Tage-Banns kassiert hat...dann dürfte sich Spieler 'Fank' ja über ein paar Tage Pause freuen, oder? Ganz blizzlike

**Comment by testear** [comment]
Dann wär das wohl so, wenn er keine Quellen bringen kann die belegen, dass das ging. Ich bin der Meinung, dass das schon gehen sollte aber verboten war.

Interessant ist das hier übrigens:

https://cynwise.wordpress.com/2011/08/17/fence-jumping-in-wsg-and-terrain-exploits/

Es geht zwar hier um ein Loch im Hordezaun und es ist ein Beitrag von 2011 aber es passt einfach zu gut zum Thema hier. Die wichtigten Stellen kopiere ich einfach mal hier rein:

"...It’s a little odd, then, that Blizzard GMs have finally come out and started saying that this jump is illegal and will get you a warning and a ban:

    _“Hello Dakoduh! My name is Game Master Rodoux. I’m going to need you to refrain from hopping up there on the fence in Warsong Gulch.” This was followed by a temporary ban when the request was not honoured.

In addition to the GM whispers, twinks are reporting that people are getting disconnected mid-jump. I haven’t had it happen to me yet (and I have jumped the fence in the past week, I FC at level 70 after all) but I’m sure it’s probably a matter of time..."

"...Yet… it’s been in there since WSG launched six years ago, and it’s something that tactics and strategies have adapted around. It’s one of the quirks of the terrain, just like the rocky patches around the zerk huts or kiting melee around the tree stumps while firing at them. Your opponents will use it against you, so you better know how to do it in response. It’s been reported many times on the forums as a bug, but has never been fixed. So folks do the jump...."_

Aktuell wäre es - was ich so gar nicht lustig finde - sogar wirklich Blizzlike dafür einfach nur Banns auszusprechen.

**Comment by dagochen** [comment]
Macht doch einfach im Zweifelsfall ein Video von der Aktion der besagten Spieler und meldet diese an Dotox und sein Team. Wirkliche Nachweise, was damals nicht ging oder ging sind halt schwer (oder garnicht) zu finden. Da hilft dann nur noch, die Serverleitung zu Rate zu ziehen und sich an die Serverrichtlinien zu halten.
