### ISSUE TITLE
Waffenskill und Hitrating.

### ISSUE THREAD

**Issue by Zutox** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1659]
Welches Verhalten wird beobachtet?
Hin und wieder verfehlen Angriffe auf Bosslevel targets trotz +8 Waffenskill durch Obsidian Edged Blade (http://datenbank.classic-wow.org/?item=18822) und 6% hit. Beobachten konnte ich dies bei Jin'do(http://datenbank.classic-wow.org/?npc=11380) und Hakkar(http://datenbank.classic-wow.org/?npc=14834) mit Hinrichten(http://datenbank.classic-wow.org/?spell=20662), und bei High Priestess Mar'li(http://datenbank.classic-wow.org/?npc=14510) mit Blutdurst(http://datenbank.classic-wow.org/?spell=23880).

Wie sollte es sich verhalten?
Bei 300 Waffenskill, also +0 Waffenskill über Items sollte das Hitcap bei 7% + (Defense Skill - Weapon Skill - 10)*.4%, also 9%. Bei 308 Waffenskill greift jedoch eine andere Formel: 5% + (Defense Skill - Weapon Skill)*.1%, also 5,7%. Demnach sollten mit 6% keine Angriffe mehr verfehlen.

Schritte zur Reproduzierung
Mit besagter Waffe an einen Boss stellen und Skills verwenden, bis einer verfehlt.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://vanilla-wow.wikia.com/wiki/Hit <- Formeln
http://imgur.com/a/63Rwq <-Screenshot

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by hraesvelgr** [comment]
wie kommst du auf das hitcap von 7% bei zweihandwaffen?

**Comment by dagochen** [comment]
7% sind 5% + 2% (strafe), für zu hohe differenz von waffenkunde und verteidigungswertung.

**Comment by testear** [comment]
1. Das Vanilla-WoW-Wiki ist keine verlässliche Quelle. Jeder kann dort ohne, dass es dokumentiert wird, editieren. http://vanilla-wow.wikia.com/wiki/Hit 
Bitte lies dir den ersten Satz nochmal durch. Falls es bis morgen frühe gelöschst ist: Dort steht jetzt 
"testear edited here to prove a point." Falls du mir nicht glaubst kann ich das gerne wiederholen.
2. Die Theorie, dass das Defrating von Mobs vom Level abhängig und bei Bossen auf 315 ist ist nicht wahrscheinlich nicht gültig.
http://wowwiki.wikia.com/wiki/Talk:Weapon_skill

> -- 13:47, 3 August 2006 (EDT)2 things that aren't accurate in the Wiki article:

"A glancing blow only occurs on white damage, can not crit and has a damage reduction proportional to the difference between the attacker's weapon skill and the target's defense."

That's not confirmed. All we know is that we have 40% chance of getting a glancing blow on non-special attacks; and that the damage reduction becomes ~0% when you reach 310 weapon skill. If you say proportional, that would mean you're saying raid bosses (who we all suppose are level 63) have 310 defense. That is NOT the case.


Second:

"With no +skill/+hit gear on, a dual wielder vs a level 63 mob will have the following damage table from the front: 5.6% dodge, 5.6% parry, 24.6% miss, 5.6% block, 40% glancing blow, 18.6% combined hit + crit. Attacking from the back prevents block and parry giving 29.8% combined hit + crit. Attacks from the back can still be dodged."

Is flat out wrong. The numbers come from thinking "since it's a raidboss lvl 63, he has 315 defense". If that was all he had, and no additional modifiers, +6 toHit in form of talents and/or gear would be enough to never miss a special attack. It is not.

315 defense theory wrong

That is a screenshot with 5/5 precision, and +1 to hit gear vs. Onyxia lvl 63. Note the 4 Sinister Strike misses in recap. Also note that recap does not count dodges or parries from onyxia as misses - the /combatlog from that fight confirms the 4 misses. That proves that 315 defense - 5,6% miss chance is not all there is against raidbosses.

Collected numbers seem to point at +8 to Hit with gear or talents to be enough to never miss a special against a boss. Numbers i collected show no misses in over 20 million points of damage over several weeks. While that doesn't prove +8 is all you need (it could be a statistical fluke making me not miss, although there is a 0,6% misschance (random number, only for the example), what is proven is that raidbosses do not have 315 defense only with no additional things being factored in.

That leaves at least 2 choices: 1) raidbosses have 300 defense, and cause an artificial 3% misschance. (having 315 defense +3% would very likely have shown a miss until now) 2) Raidbosses come with a bonus 60 defense, raising it to 375 - which leads to the observed needed +8 toHit to never miss, and is in a way supported by the high parry and dodge chances bosses seem to have (although that is as of now an impression, and not backed up by numbers)

Unless there is feedback or comments soon, I'll implement my findings into the Wiki page, because right now it's spreading disinformation. Also: "nice findings" is cute and all, but I'd prefer a proof that i am wrong if i am.

Small note: this information does not invalidate the findings about crit/hit vs glancing blows.

--- Assassinette

**Comment by dagochen** [comment]
>7%+(315-300-10)x4%=0,27
5%+(315-308)x1%=0,12

Du hast den Punkt vergessen. Die Formeln sind im offiziellen cmangos auch exakt so implementiert.
7%+(315-300-10)x0,4%=0,09 = 9%
5%+(315-308)x0,1%=0,07 = 7%

https://github.com/cmangos/mangos-classic/blob/master/src/game/Unit.cpp#L2723

**Comment by testear** [comment]
Das ist richtig, ich hab den Punkt übersehen..

"Sieht für mich also alles richtig aus, bis auf den Punkt, dass wir nicht wissen woher die Fehltreffer herkommen?"
Siehe Punkt 2. Englischkentnisse erforderlich!

**Comment by dagochen** [comment]
Ach das ist dieser super-lange Artikel mit Dutzenden Theorien. Ja da sind viele gute Ansätze und Ideen drin, das meiste wird leider nicht mit Fakten belegt. Ich weiß nicht, wie man aus dem was rausholen kann. Ich denke unsere Formeln sind nicht falsch, sondern viel mehr, dass da irgendwas im Server bei uns dazu geführt hat, das z. B. falsch gerundet wurde an irgendeiner Stelle oder irgendeine andere Kleinigkeit dafür sorgt, dass trotzdem ein Treffer mal daneben geht. Das aber rauszufinden wiederum ist enorm aufwendig und bei 0,x% Fehltreffern auch nicht so wichtig.

**Comment by testear** [comment]
Als ich das letzte mal nachgeguckt habe waren die Werte für Dualwielder richtig.

https://docs.google.com/spreadsheets/d/1fvHQVDpEHjFdG9ANtAOAk5zR1RaKqMDWi5psRcHvJ_Q/edit?pref=2&pli=1#gid=0

(Credits to Citruzz)

**Comment by Hakii** [comment]
Autoattacks sollten bei den geschilderten Zahlen von Zatox nicht verfehlen. Styles hingegen treffen durch Waffenkunde nicht besser, sprich hier muss immer das klassische Style-Hit-Cap erzielt werden.

**Comment by testear** [comment]
Aber leider sind so Theorien in den Comments von WoWWiki, die genau das beschreiben, ja keine Fakten.

Achtung Ironie.

**Comment by Hakii** [comment]
Aussagen über den Attacktable in Vanilla können grundsätzlich nicht oder wirklich nur in Ausnahmefällen mit Fakten belegt werden, da der  Attacktable in fast sämtlichen Belangen erst nach 2.0 entschlüsselt wurde und sämtliche vorangegangen Annahmen zu 95% revidiert wurden. Allerdings wurde der große ZG-Test zwischen Patch 2.0 und 2.3 - dem Waffenkunde-zu-Expertise-Patch - durchgeführt, weshalb man von der Richtigkeit ausgehen kann. Bis Dato war die Funktionsweise von Waffenkunde gegenüber Zielen auf demselben Level oder höher gänzlich unbekannt bzw. nicht nachweisbar und faktisch unfundiert.

Dennoch: Da CMANGOS über einen nahezu einwandfreien Whitedamage-Attacktable verfügt und über dasselbe Styleproblem verfügt, wie es aus dem Comment des Schurken zu entnehmen ist, scheint die Mechanik auf unserem Server entsprechend des Originals zu funktionieren.

Spontan würde mir nur eine mögliche Fehlerquelle einfallen, über die man noch einmal einen Blick werfen könnte. In den früheren Tagen wurde eine Misschance gegen Bosse von 5,6% vermutet (Waffenrating wurde bei der Bestimmung dieser Zahl völlig außer acht gelassen). Eventuell wurde diese Zahl fälschlicherweise als Basismisschance bei Styles verwendet (anstatt der korrenten 5,0% + Differenz zwischen Defense und Waffenrating)

**Comment by dagochen** [comment]
>Collected numbers seem to point at +8 to Hit with gear or talents to be enough to never miss a special against a boss. 

Mich wundert grad die Aussage über 8% Hit, die in den Beiträgen als cap genannt werden. Im Mangoscore kommt man aber auf ein Hitcap bei 9%.

**Comment by Hakii** [comment]
> Mich wundert grad die Aussage über 8% Hit, die in den Beiträgen als cap genannt werden. Im Mangoscore kommt man aber auf ein Hitcap bei 9%.

Es werden keine Angaben über Rasse, Waffen und Waffenrating gemacht. Er selbst ist ja auch der Annahme, er habe Glück gehabt, dass er nicht gemissed hat über 20mio Damage. Weiterhin arbeitet der Schurke sowieso mit falschen Zahlen.

**Comment by testear** [comment]
Whoah, das nimmt tolle Ausmaße hier an.

Aber aus unserem Jägerforum wird ersichtlich, dass 9% für Styles (zumindest für Jäger) schon fast zwingend nötig sind. 
Was Hakii zu den Styles für Melees auf Nefarian sagt (8%Hit=0%Miss) kann ich bestätigen. Dennoch kann das natürlich auch nur eine Anomalie in der Statistik sein. (Ich habe damals nur die Bosse in ZG als Testobjekte genommen.) In Sabbaers Retriguide werden aber auch nur 8% Hit empfohlen.

Ich würde schon gerne wissen woher da der Unterschied kommt.

**Comment by Haudraufinix** [comment]
Der Unterschied im Hitcap für Hunter und Melees resultiert daraus, dass ranged attacks keine glancing blows verursachen können. Damit Jäger nun nicht einfach Mobs töten die 15 level über ihnen sind, hat sich Blizz entschieden, dass die Hitchance vom Jäger mit grösserem Waffenkundeunterschied stärker abnimmt.
Hier der Post zu Waffenkunde für Jäger: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1018

Ich empfehle in diesem Post ganz klar den Fokus auf melee Waffenkunde zu legen, da Hunter Waffenkunde bereits korrekt implementiert ist.

**Comment by dagochen** [comment]
Was ist denn nun für Classic korrekt (wie MUSS/SOLL es sein)? 8% oder 9% Misschance gegen Bosse bei 0 % Hitgear und 300 Waffenkunde?

**Comment by Sabbaer** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/813

**Comment by dagochen** [comment]
@Sabbaer In dem Beitrag geht es aber um Glancings, nicht um Misschance. Lasst uns bitte nicht alles durcheinander werfen, dann wird es nur noch unübersichtlicher. Am liebsten wär mir, wenn jemand mit Quellenverweis zeigen kann, dass 8% oder 9% richtig oder falsch sind. Nur dann kann man ggf. was daran ändern. Was steht denn in alten Klassenguides für z.B. 2Hand-Krieger oder Paladine drin?

**Comment by hraesvelgr** [comment]
was ich denke, ist (und so kenn ich es), dass man 8,6% hit braucht. da es jedoch nicht möglich ist, ohne waffenskill kommastellen zu stacken, hat man entweder 8% genommen, und auf die kommastelle geschissen, oder das hardcap von 9%. was dann jedoch wieder eine theoretische verschwendung on werten war.

**Comment by Horim** [comment]
Zu den 8% Hit für Styles: 
Hat bei mir als Undead ohne +Waffenskill nicht gereicht.
Mit 8% hatte ich immer wieder "Miss" auf Styles (z.B. Blutdurst) bei Firemaw in BWL -_-'.
Mit 9% konnte ich noch kein "Miss" feststellen, die Wahrheit liegt wohl irgendwo dazwischen,

**Comment by Hakii** [comment]
> Du hast den Punkt vergessen. Die Formeln sind im offiziellen cmangos auch exakt so implementiert.
> 7%+(315-300-10)x0,4%=0,09 = 9%
> 5%+(315-308)x0,1%=0,07 = 7%

Fakt ist, dass diese Formel in Sachen Whitedamage wunderbar auf dem Server aufgeht. Da ich im cmangos selbst keine Differenzierung zwischen Abilities und Autoattacks gefunden habe, sollte diese Formel ebenso für Styles Verwendung finden. Dennoch haben wir ein wenig mit Waffenkunde und Hit im Gear herumexperimentiert und herausgefunden, dass Waffenkunde aktuell keinen Einfluss auf Styles hat, egal ob mit 300, 305 oder 310  (Beispiel: Bei 310 Waffenkunde wurde mit 6% Hit probiert und es wurde gemisst / theoretisches Hitcap 5,5% für Styles in dem Fall). Seltsam war hier allerdings lediglich, dass mit 8% keine Misses mehr getracked wurden. Fakt ist aber auch, dass zur Datenerhebung keine 10.000 Hits oder ähnliches gemacht wurden und somit eine Anomlie nicht ausgeschlossen werden kann.

**Comment by Seniorash** [comment]
irrelevanter Report. 5% basemiss 1% pro lvl und 0,2% pro 5 def-wk Rating Differenz. genau so ist es hier auch. mit 8% hast du hier definitiv noch misses

**Comment by dagochen** [comment]
Die Mehrheit der Meinungen geht hier ja in die Richtung, dass es alles korrekt ist, dann kann ich hier zu machen oder?

**Comment by testear** [comment]
Denke ich auch @dagochen 

Interressant ist noch die Frage woher die 1% Differenz herkommen: Horim berichtet von Misses mit 8%, während Hakii und ich da schon keine mehr gemessen haben. Damit wären wir wieder bei der Anomalie in der Statistik. Vermutlich liegt die Wahrheit wirklich irgendwo dazwischen. Die einzige Möglichkeit wäre halt exzessives testen. Dass die 8,6% Mathematisch nicht ohne weiteres zu erschließen sind, hatten wir schon festgestellt und und da das früher auch schon festgestellt wurde sehe ich da kein Problem.
