### ISSUE TITLE
Krieger waffen proc´s und windfury proc

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1774]
Welches Verhalten wird beobachtet?
Es scheint so das die Krieger fähigkeiten Schildschlag, Schildhieb, Abfangen und Zuschlagen, Donnerknall und (Anstürmen - da bin ich mir nicht sicher ob es da möglich ist) waffenprocs und wf auslösen können. 
Alle diese Fähigkeiten (bis auf Anstürmen) machen unabhängig zur waffe Schaden und könne waffen procs auslösen.

Wie sollte es sich verhalten?
Das sollte nicht möglich sein da für diese Zauber keine Waffe benötigt wird und auch nicht mit der waffe zugeschlagen wird.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Eigentlich war mir aufgefallen das auf Abfangen sehr häufig waffen procen, was durch diesen bug dann auch die doppelte chance hätte. Doch habe ich es dann mit Zuschlagen getestet da abfangen buggy ist.
Ich habe erst angegriffen, 1 sekunde gewartet und dann zuschlagen gewirkt.

http://www.directupload.net/file/d/4503/76ahi8i7_jpg.htm

http://www.directupload.net/file/d/4503/8565awjf_jpg.htm

-Beachten sollte man das diese bug dann das Windfury totem und andere waffen verzauberungen (proc öle, kreuzfahrer usw) betrifft.
-Die krieger talente Streitkolben-Spezalisierung und Schwert-Spezalisierung sind davon auch betroffen
-Waffenprocs werden dadruch auf häufiger ausgelößt. Hevor zu heben ist dabei Dunkle Schneide des Irrsins.

Damit will ich nur sagen das das aktuelle abfangen immer eine doppelte chance hats procs aus zu lösen die auf der waffe basieren.

Noch eine kleine information am rande....der bug ist generell ein Privat server problem und ist auf verscheidenen severn zu beobachten.

**Comment by testear** [comment]
Dass die Schwertspezialisierung Proccs auslösen kann ist erst mit BC entfernt worden.
Siehe https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/969

**Comment by SirBeansen** [comment]
Also hier sollte es nicht darum gehen ob der Schwerspec einen proc auslösen kann sonderns das Der Schwertproc duch fähigkeiten ausgelöst wird die gar kein Schwerthieb machen ;)

**Comment by Badorr** [comment]
Shield Slam und Shield Bash sollten Waffenproccs auslösen können. Das wurde erst mit 2.0.1 entfernt

"Warrior "Shield Slam" and "Shield Bash" will no longer trigger a proc from an equipped weapon. "

http://wowwiki.wikia.com/wiki/Patch_2.0.1

**Comment by testear** [comment]
Es fehlen eh Quellenangaben die für eine Bearbeitung nötig sind.

**Comment by SirBeansen** [comment]
Naja du findest dazu keine Quellen weil es wohl nie da gewesen ist. Aber das mit Shield Slam und Shield Bash ist natührlich interessant. Aber wenn man davon ausgeht das Charge/intercept und die anderen non weapon spells, procs auslösen könnten dann würde man das doch nun auf den live server noch sehen müssen bzw dann wüssten die Spieler doch das man eine erhöhte proc chance hat wenn man den gegner anstürmt.

Auch wenn man sich einige classic warrior videos ansieht kann man nicht sehen dass irgendwann ein wf oder waffen proc während des chargen ausgelöst wird.

-----------------------------------------------------------------------------------------

Schwert-Spezialsierung
Gewährt Euch eine Chance von 5%, einen zusätzlichen Angriff auf das gleiche Ziel zu erhalten, nachdem Ihr mit Eurem Schwert Schaden zugefügt habt.

Wieso reicht das Talent als Quelle nicht? Wf totem verzaubert auch die waffe und Crusader ist auf der waffe verzaubert, denoch proccen sie obwohl man mit der Faust zu haut.

Charge ist auch davon betroffen das es meiner vermutung sogar auf den Stun effekt procen kann, gleiche wie bei abfangen.

Ich kenn mich ja mit den codes und so gar nicht aus aber kann man da nicht rein schauen ob da was auffäliges steht?

Bei http://datenbank.classic-wow.org/?item=11815 steht sogar zb extra dabei das es einfach nur ein melee hit benötigt.

Es ist einfach zu auffälig das Bei einem charge/abfangen ein waffen proc deutlich öfters kommt als wenn man nur zu haut.

Aber ich versteh schon das man da ohne genaue Quelen nichts ändern will...aber man findet auch nichts dazu das Charge/intercept waffen proccs auslösen können. Auch nicht in videos. 

Knochenhäschers Schneide wurde zb auch geändert weil es zu broken war.
Pala t1 8set boni wurde auch geändert weil es zu broken war.

**Comment by testear** [comment]
Erstens wirds nicht geändert, weil du der Vorlage nur da Entsprichst wo es dir gefällt. 
Zweitens gilt dein Wort genausowenig wie meins als Quelle. Solltest du wissen. 
Drittens ist es nicht richtig, dass eine auf PPM basierende Mechanik durch ein paar Fähigkeiten die sie möglicherweise Fehlerhaft Proccen die Proccchance drastisch erhöhen.

**Comment by Seniorash** [comment]
Abfangen und Charge lösen 100% nichts aus. Blutdurst als Angriff ohne Waffe ebenfalls nicht. Bei Donnerknaöl Blutdurst zuschlagen hatte ich in 3 Jahren noch keinen Proc. Sieht eher nach einem Frustreport aus

**Comment by testear** [comment]
Ernst nehmen muss man es trotzdem.

**Comment by dagochen** [comment]
Hab letzte Nacht permanent abfangen gemacht und keine Procs gehabt. Ich glaube nicht, dass hier etwas buggy ist, kann es aber nicht 100% ausschließen. Bis es eindeutige Quellen für ein falsches Verhalten des Servers auf Grundlage von Nachweisen von damals gibt, mach ich hier mal zu.

**Comment by SirBeansen** [comment]
Gerade auf dem testserver die neue trap mit dem delay ausprobiert. Wollte sehen wie es sich mit dem chargen verhält. Und während des chargen ist die waffe "Der Zertrümmerer" geproct, obwohl der warry in die trap gecharged ist und somit auch kein auto attack langen konnte. Das ist defentiv falsch und zeigt auch das Senirorash kein besonders aufmerksamer spieler ist, erst recht weil ich auch schon bewiesen habe das Zuschlagen den schwert proc triggern kann.

**Comment by testear** [comment]
Keine Quellen= Kein Fix

"Das ist defentiv falsch und zeigt auch das Senirorash kein besonders aufmerksamer spieler ist, erst recht weil ich auch schon bewiesen habe das Zuschlagen den schwert proc triggern kann."

Zeigt nur, dass du keine Ahnung hast was in einen Report gehört und was nicht. Ich habe oben bewiesen, dass ein Angriff ohne Waffe Kreuzfahrer proccen können sollte. 
Ich habe btw keine Quellen gefunden die belegen, was du sagst. Ich bin aber gerade auch mit anderen Dingen in meinem Leben beschäftigt. Du scheinst aber die Zeit dafür zu haben, also such bitte Quellen zu dem was du behauptest.

**Comment by SirBeansen** [comment]
Naja die einzige Quellen sind die pvp videos, weil du da niemals einen charge procc sehen wirst, weil es nicht möglich ist und zu broken ist. Während man hier ganz easy den fehler beobachten kann. Du hast gezeigt das Blutdurst eventuell einen waffen proc aus lösen konnte das ist auch sehr gut..aber heißt nicht das jeder non weapon spellt das auch sollte.

Auserdem fordere ich keinen sofortigen fix...man kann ja auch einfach normal drüber diskutieren? ich versteh nicht warum ihr darauf so niederschmättern reagiert, anstatt die sache mit verstand anzugegen das die proc chance von waffen durch charge einfach mal verdoppelt werden und einfach broken sind.

Senirosah hat gemeint im wäre noch nie ein proc während des chargen aufgefallen und wenn man genau hinschaut und es provoziert dann erkennt man es auch, also braucht er gar nicht mit seiner 3 jahren langen erfahrung ankommen.

**Comment by testear** [comment]
Ich reagier nicht niedergeschmettert darauf was du sagst, mich stört, dass du meckerst ohne es belegen zu können. Kümmert mich auch eigentlich erst dann wenn es denn "gefixt" wird. Klar es macht einen riesen Unterschied ober Kreuzfahrer beim Charge procct oder beim Schlag vom procct. Total OP und völlig Broken! Nicht.

**Comment by SirBeansen** [comment]
Ja das habe ich auch vor nur hab ich zurzeit kein video editor. Auserdem hab ich den Zuschlagen schwert proc bewießen, nur nicht ob es wirklich ein bug ist. Doch auch andere bugs wurden schon durch verständnis und durch tooltips gefixt. Soll ja nicht heißen das es nun hier auch so gemacht werden sollte ;)

Und ich glaube nicht das ich mir von einem nicht pvpler erklären lassen muss was broken ist und was nicht =) Eine erhöhte proc chance auf einen waffen effekt (nicht vz) oder spezialsierung + den dazugehören swing timer reset ist broken.

**Comment by testear** [comment]
"Und ich glaube nicht das ich mir von einem nicht pvpler erklären lassen muss was broken ist und was nicht " 

Du bist ein Troll und ein schlechter dazu,

**Comment by Horim** [comment]
Blutdurst erzeugt keine Windfury proccs, schon tausend mal getestet.

**Comment by testear** [comment]
Okay, dann nutzt mal euren Kopf um das hier aufzulösen:

http://wowwiki.wikia.com/wiki/Proc?oldid=328734
WoWWiki spricht von 3 unterschiedlichen Proccarten:
Proccs durch Waffen (Verzauberungen und Waffenproccs), Proccs durch Ausrüstung (Rüstung, Ringe, Trinkets) und Proccs durch Fähigkeiten (Dornen, Feuerschild, Totems, Paladinsiegel etc.).

http://www.elitepvpers.com/forum/wow-guides-templates/45008-weapon-enchantment-procs.html
How can I abuse PPM to my advantage?
------------------------------------------
Two words - Instant Attacks. When you use an instant attack (skills that do &#39;weapon damage + X&#39; like sinister strike and mortal strike) it counts as hitting with your mainhand/two-hand weapon. No matter the speed of your weapon, you will always be using instant attacks at the same rate. Because of the fact that the slower a weapon&#39;s speed is, the higher the %chance to proc a PPM enchantment on it, your instant attacks have a higher chance to proc an enchantment if they are slow.
(Was den WoWWiki Post zum Proccen von Kreuzfahrer auf Blutdurst widerlegt.)

Meiner Meinung nach ist es so, dass Waffenverzauberungen (Kreuzfahrer, Lebensdiebstahl, etc) nur auf Fähigkeiten proccen die Waffenschaden+Fähigkeitenschaden verursachen.

Proccs von Ausrüstung sollten durch alles Proccen können. 

Bleibt also noch die Möglichkeit der Proccs durch Fähigkeiten die diesen Report betrifft:
"Some spell effects can also grant players a proc. Examples: The Druid spell Thorns grants the player a proc that damages his attackers when they strike him. The Warlock's Imp spell Fire Shield is similar to Thorns. The Shaman spell Windfury Totem causes each attack to have a chance of permitting a free attack with a bonus to their attack power. Both the Paladin seals Seal of Command and Seal of Righteousness have a chance on hit to cause holy damage (though in very different ways). "

Schwert- und Kolbenspezialisierung dürften wie SoC zur Chance on Hit Kategorie gehören. Bedeutet, dass nur wenn Waffenschaden (mit Kolben oder Schwert) hinzugefügt wird sollte es auch Proccen. Demnach eben nicht, wenn Pummel, Charge, Intercept, Thunderclap und evtl auch Rend und Disarm gewirkt werden.
Übrigens auch nicht auf die Proccs von Sweeping Strikes.
https://hilbert.wordpress.com/sweeping-strikes-guide/
It is worth noting that SS cannot miss, be dodged, parried nor blocked, but as of patch 1.11 can crit. It cannot proc things like Crusader, Sword Specialization, Hand of Justice and similar effects. It does not generate any rage – only white attacks do.

Die Schlussfolgerung bleibt natürlich den Devs überlassen.

Aber was ich jetzt gerne hätte wäre eine Erklärung lieber Beansen, Warum du das nicht kannst?
