### ISSUE TITLE
[Battleground] Flagge mit Damage Schild übernehmen

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1806]
### Welches Verhalten wird beobachtet?

Wenn man ein Priester/Mage/Hexer oder trinket Schild hat, kann man die Flaggen im Alterac sowie Arathibecken einehmen ohne das man durch direkten Schaden unterbrochen wird.

Zurzeit ist es möglich mit Priester Schild, ice barrier/Leerwandler opfern + Ouro/Arena trinket einen so hochen Schild effekt zu generieren, dass für den gegner kaum möglich ist diesen innerhalb der 10 sek tap Zeit zu unterbrechen ohne CC effekt. Und wenn man einen Schadens zauber erst noch wirken muss, hat man noch weniger Zeit.

Zudem führt es in den BG´s zu einen sehr hohen ungleichgewicht.

### Wie sollte es sich verhalten?

Man sollte auch mit einem Schild effekt bei direkten Schaden unterbrochen werden.

### Schritte zur Reproduzierung

Ins Arathibecken gehen > Priester Schild uphalten > mit einem anderen Char versuchen mit direkten Schaden (Styles oder autoattack) den gegner zu unterbrechen.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Es ist sehr Schwer dafür Quellen zu finden, doch ist mir zb gar nicht gelungen Beweiße zu finden die besagen dass es sich um keinen Bug handelt.

http://wow.allakhazam.com/forum.html?forum=21&mid=112774548691767786 

Sep 26 2005 
-As troll priest I have tried caping with my shield up and still get interuped when I get hit. So this is still looking like a pally exploit.

http://www.gamefaqs.com/boards/534914-world-of-warcraft/44812379 

8years ago
-Yeah I noticed that the other day in AB. Was capping a flag with PW:S on me and a mage stabbed me and I was interrupted.

http://www.wowhead.com/forums&topic=153563/disc-priest-pvp-how-to-interrupt-a-flag-capper
2010/04/25
-It doesn't matter if the capper is shielded or not. Any direct damage that the capper takes himself or which is absorbed by his shield will interrupt the channeling effect.

Die beiden letzten Quellen sind jetzt zwar nich von 2006, aber sollen zeigen das es auch zu späteren addons nicht möglich war mit dem Schild immun zu sein.
Wäre das in classic möglich gewesen und hätte blizzard das dann geändert, dann müsste ja was in den patch notes dazu stehen......was es aber nicht tut.

Desweiterem hab ich aus einem anderen Forum noch: 

Data mined from client files confirms it should be "interruptible by any damage" including absorbed. There are more spells with this interrupting method. but currently it is not working at all. In the next update it will be fixed and this spell (capturing the flag) will automatically become interruptible by absorbed damage.

Eventuell hilft das einen der devs? Ich weiß ja nicht was man da alles sehen kann^^

Wichtig ist das Dots nicht unterbrechen sollten!

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

http://datenbank.classic-wow.org/?item=23558 ouro Schild
http://datenbank.classic-wow.org/?item=19024 Arena Schild
http://datenbank.classic-wow.org/?spell=13033 Ice barrier
http://datenbank.classic-wow.org/?spell=10901 PW:S
-Keine ahnung wie das Warlock ding heißt ^^

**Comment by 0815Priester** [comment]
http://datenbank.classic-wow.org/?item=13603
http://datenbank.classic-wow.org/?item=13603

**Comment by Gromnir** [comment]
Das Problem tritt nicht nur beim cappen der flagge auf. Bandagieren oder sammeln von Kräutern wird auch nicht unterbrochen während man damage in einer bubble kassiert. 
Diese "channel" effecte sind keine Zauber, sondern Aktionen. Diese 2 Mechaniken muss man unterscheiden. Das macht der server im Moment aber nicht. 

2013 hab ich das alles in nem Thread schonmal angesprochen. Ich sammel mal die ganzen Zitate der Leute raus. Manche Links funktionieren leider nicht mehr und vieles stammt aus post 1.12:

Thread: https://community.mmobase.de/bugtracker-archiv/3256-[pvp]-tappen-der-arathiflaggen-mit-priesterbubble-und-eisbarriere.html

Quellen von 2006 sind hierzu leider rar. 
Nur die hier von 2005:

> Man kann mit garkeinen Schild capturen. Im AV ging das noch jetzt nichtmehr. Auf wenn man ein DMG Schild drauf hat wird man unterbrochen wenn man schaden nimmt.
Ob das bei neutralen Flaggen auch so ist weiß ich nicht. Wenn dann geht das mit dem DMG Schild auch. 

http://www.forum-3dcenter.org/vbulletin/showthread.php?t=249361
Post 15

----


> Da auch absorbierter Schaden das tappen unterbricht, kann man 
Quelle: Flaggen tappen verhindern - Foren - World of Warcraft

http://www.bloodcraft.org/phpbb/viewtopic.php?f=43&t=11422&start=0

----
> Re: Absorb effect - flag capping (battlegrounds)
Postby Slix » Mon Feb 14, 2011 8:17 pm
Actualy I do have proof, sorry for double post btw.
Read this whole thread to see how you should and shouldn't be able to prevent base cap. [url=http://www.wowhead.com/forums&topic=153563/disc-priest-pvp-how-to-interrupt-a-flag-capper]Disc priest PVP: how to interrupt a flag capper? - Priest - Wowhead Forums[/url]
here is the important bits.


> wartu
 said:
Great input peeps. I won't bother wasting time on DoTs anymore for this purpose.
The problem with wanding as I see it is that is so low damage than any class that has damage absorption abilities (priest shields, druid barkskin, paladin bubbles etc) will be able to cap easily by the time you get through the shield, if at all.
Even while shielded, they still get interrupted when dealing with the flag, afaik. At least, I always seem to.


> It doesn't matter if the capper is shielded or not. Any direct damage that the capper takes himself or which is absorbed by his shield will interrupt the channeling effect.
It's the direct damage which is the key. If a shield absorbs damage from DoTs, this will not interrupt the capper.
If you don't know how much channeling time is left, a quick penance or SW:D will do the job. If the capper makes additional tries, you can just wand him since you'll know that there's more than enough time to wand him.

----

Bzgl Cappen hier ein Cache-Beitrag aus dem offiziellen WoW-Forum von 2009:

>     Q u o t e:
title says it all. It prevents spell interrupts (supposedly), why doesn't it prevent interruption from capping a flag?

/

> Because you're not casting a spell, you're capping a flag.
No class can be uninterruptable while capping a flag.
Because that would be a monumental advantage in a BG, as well as colossally unfair.
also, vw sac prevents spell pushback, not actual Interrupt abilities. I can still spell lock you when your shield is up.
There's no pushback when capping a flag, any direct damage simply cancels the action.
This thread was on the old WoW forums that have since been closed.


[url=http://www.threadmeters.com/wow/kRhJSE/VW_bubble_should_prevent_flag_cap_interupts/] VW bubble should prevent flag cap interupts - World of Warcraft | TM[/url]

----

Über bandagieren:
> "Bandaging is a channeling effect. Taking damage while bandaging, be it from a direct attack or a DoT, will severely reduce the amount healed by interrupting the application of a bandage. However, unlike other channeled effects, damages absorbed by a shield will cancel it."
Quelle: [url=http://www.wowwiki.com/First_Aid]First Aid - WoWWiki - Your guide to the World of Warcraft[/url]
Mit "Other channeled effects" sind Zauber gemeint und nicht channeleffekte von Gameobjekten.

----

Es wurde damals nicht geändert weil die Beweise nicht genügten bzw. nicht alle von 1.12 Zeiten stammen oder zu vage waren. 
Vielleicht ist das jetzt alles überzeugender nachdem Nostalrius das bei sich schon implementiert hatte^^

**Comment by dagochen** [comment]
Alles was nicht 1:1 das gleiche Verhalten wie die Flaggen haben bitte mal löschen, sonst kommt man hier durcheinander.

**Comment by dagochen** [comment]
Ich mach hier mal zu, da hier nix mehr kommt.

**Comment by dagochen** [comment]
Umgeändert
