### ISSUE TITLE
Verzauberung Kreuzfahrer und Katzenform

### ISSUE THREAD

**Issue by swbulldog** [ClassicWoW/Nefarian_1.12.1_Bugtracker#605]
Die Verzauberung Kreuzfahrer proct nicht in Tiergestalt als Druide

**Comment by wahaxlekuke** [comment]
Bitte ließ dir mal die Readme-Datei durch: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker

Was vor allem fehlt ist eine Quelle für den Bugreport. Ich glaube außerdem, dass das gar kein Bug ist, sondern bis zu wotlk einfach so war.

**Comment by hraesvelgr** [comment]
als katze und bär schlägt man nunmal nicht mit seiner waffe zu, sondern mit seinen tatzen, deshalb funktionieren waffenprocs nicht. das wurde erst mit wotlk (3.0.0) reingepatcht

**Comment by Haudraufinix** [comment]
1. mal ein unzureichender Bugreport 2. war das zu classic so. WAFFENPROCCS und verzauberungen, welche wie Waffenproccs wirken funktionieren für Fernkampf und Katzengestalt nicht
"krynble on 2008/03/17 (Patch 2.3.3)
Permanently enchant a melee weapon so that often when attacking in melee it (THE WEAPON) heals for 75 to 125 and increases Strength by 100 for 15 sec. Again: it cannot procs on shapeshifted druids. Go for savagery or +35 agi if you're a druid. "
Quelle: http://www.wowhead.com/spell=20034/crusader#comments wurde erst zu wrath von Blizzard geändert

**Comment by Larnak1** [comment]
Das von swbulldog beschriebene Verhalten ist tatsächlich absolut korrekt und gehört zu den Besonderheiten des Druiden, siehe hraesvelgr.
