### ISSUE TITLE
bug report siegel des befehls +richturteil -krit

### ISSUE THREAD

**Issue by lysop** [ClassicWoW/Nefarian_1.12.1_Bugtracker#607]
hi 
ich möchte einen bug melden  siegel des befehls und das richtruteil des befehls betrifft,
diese können nicht mehr kriten !!

**Comment by Haudraufinix** [comment]
Aua meine AUGEN!
 
Zauberschaden skallierung:
Seal of Command receives 20% coefficient from normal +spell damage stats, and 29% from +holy damage stats (such as Judgement of the Crusader). Judgement of Command receives 43% coefficient from any +spell damage stats.

Hitchance:
Unlike other spells, Seal of Command and Judgement of Command are considered physical hits, that does Holy damage. They both use melee crit and hit stats instead of spell crit or hit, and when they crit the damage will be multiplied by two. However like other physical attacks, Seal of Command can miss, or be dodged, parried, or blocked. Judgement of Command can only be resisted.

Quelle: http://www.wowwiki.com/Seal_of_Command_(old)?oldid=399352

**Comment by lysop** [comment]
siegel des befehls und richturteil muss die möglichkeit haben zu kriten und das tut es eben nicht mehr !

**Comment by Nobugsanymore** [comment]
ich bitte um close und um seine weiteren beiträge (report was palas an geht nicht zu beachten da er weder erfahrung noch ahnung von der klasse hat )

**Comment by hraesvelgr** [comment]
dreh doch mal nicht gleich frei... wenn siegel udn richturteil nicht mehr critten, kann das evtl einen grund haben. 

bei mir geht es auch nicht. hier sogar der screenshot-beweis:

![wowscrnshot_033115_181309](https://cloud.githubusercontent.com/assets/9222522/6923525/98050e64-d7d2-11e4-8044-aea0a007a177.jpg)

die unterstrichenen werte zeigen an, wieviele crits (x)  es gab, sowie die anzahl aller hits mit dem jeweiligen spell (y). also:

x/y

**Comment by Acolatronico** [comment]
seit diesen sonntag? wurde doch was am siegel des befehls geändert wegen parrieren wiederstehen usw, seit dem tag jedenfalls können "siegel des befehls proc" und richurteil des befehls" nicht mehr criten. hatte seit sonntag bis heute abend im raid 0 crits , nur auto hit critet normal

**Comment by Haudraufinix** [comment]
kann es sein, dass das Siegel vielleicht mit dem Autohit Crit "soft critet" -> sprich Crt Schaden verursacht, da höherer Waffenschaden aber selbst nicht als kritischer Effekt angezeigt wird?

**Comment by Acolatronico** [comment]
wie gesagt 0 crit chance auf proc und richurteil seit dem wochenende , kann man einfach mit einem duell nachtesten wenn der andere spieler sitzt

**Comment by Larnak1** [comment]
Dass kein Crit angezeigt wird, hat Haudraufinix doch selbst schon geschrieben.
