### ISSUE TITLE
paladin: siegel des befehls proc und richurteil können zurzeit nicht criten

### ISSUE THREAD

**Issue by Acolatronico** [ClassicWoW/Nefarian_1.12.1_Bugtracker#612]
Welches Verhalten wird beobachtet? 
seit diesem samstag/sonntag können der "siegel des befehls proc " und "siegel des befehls richurteil" nicht mehr criten. anscheinend wurde an einem der beiden tage irgendwas an der datenbank geändert.

Wie sollte es sich verhalten?
der siegel des befehls proc und das richturteil sind abhängig vom meele crit wert und sollten kritische treffe auslösen können.

Schritte zur Reproduzierung
duell starten, target hinsetzten lassen, richurteil des befehls wirken welches zu 100% chance criten sollte.

Links aus unserer Datenbank
http://datenbank.welli-it.de/?spell=20920
http://datenbank.welli-it.de/?spell=20947

**Comment by Ghulfang** [comment]
sitzende Ziele bekommen hier auf diesem Server keine Crits

**Comment by Frostlatte** [comment]
Laut Datenbank ist der genannte Procc kein Physischer sondern ein Holy. Müsste er demnach nicht von der ZauberCritChance abhängig sein? 

 http://datenbank.welli-it.de/?spell=20424

Beste Grûße, Frost

**Comment by Haudraufinix** [comment]
nein Frost, BoC ist ein Melee basierter Zauber, dass er von melee Crtchance profitiert, stimmt schon
*
Unlike other spells, Seal of Command and Judgement of Command are considered physical hits, that does Holy damage. They both use melee crit and hit stats instead of spell crit or hit, and when they crit the damage will be multiplied by two. However like other physical attacks, Seal of Command can miss, or be dodged, parried, or blocked. Judgement of Command can only be resisted.
*

Quelle: http://www.wowwiki.com/Seal_of_Command_(old)?oldid=399352
Wir alle wollen Palanervs, aber wir machen's richtig ;)
