### ISSUE TITLE
Noggenfogger Elixier

### ISSUE THREAD

**Issue by DarkMueke** [ClassicWoW/Nefarian_1.12.1_Bugtracker#659]
Die Effekte von Noggenfogger sind buggy und zwar konnte man zu Classic Patch 1.12.1 noch nicht in Skelett und Geschrumpfter Form auf's Mount aufsteigen. Es funktionierte lediglich mit dem Effekt "Leichterfall".

Diese Effekte "Skelettform" so wie "Geschrumpft" ist im PVP ein grosser spielerischer Vorteil. Könnte man nicht mehr aufmounten, was eigendlich der Fall sein sollte, wäre dieser Vorteil nicht vorhanden!

Die Quellen: http://www.wowwiki.com/Noggenfogger_Elixir

Patch 5.0.4 (28 August 2012): Players may now use mounts while under the skeleton effect.

3.3.0 (08-Dec-2009): Players shrunk while under the effects of this item will now be able to mount.

Vielen Dank für's Bearbeiten

DarkMueke

**Comment by bugreportor** [comment]
Hier der Link zur Datenbank: http://datenbank.welli-it.de/?item=8529
Das ist aber ohnehin eine Fehlinformation. Das ging auf jeden Fall zu classic.
https://youtu.be/PiubZPPTUJI?t=1m31s 
Ab Minute 1:31 geschrumpft auf dem Mount
https://youtu.be/PiubZPPTUJI?t=4m38s 
Ab Minute 4:31 geschrumpf als Skelett auf dem Mount.

**Comment by SirBeansen** [comment]
wo erkennst du ab 4:31 das er als skelett auf den miount sitzt?

Ich kenn das nur so das man geschrumpft auf den mount reiten konnte, aber nicht als skelett und das ging auch nicht in tbc

**Comment by Flaktrack** [comment]
Paar alte Thottbot Kommentare:
http://web.archive.org/web/20070317175923/http://www.thottbot.com/i8529

z.B.:

17.03.2007 minus 11 Monate:
"I'm not sure if it works for all races yet but drinking these until you turn into a skeleton then eat a Savory Deviate Delight will turn you into a female Pirate or ninja. 
Then you can also mount up and cancel the ninja/pirate and be a mounted skeleton."

17.03.2007 minus 9,3 Monate:
"There r 3 affects after drinking the Elixir. 
1.You turn into a skeleton which annoys me since u can't mount or ride a griffin. 
2.You become as light as a feather. If ur a mage it would be a little bit of a rip off since u could do that any time. 
and finaly. 
3. You turn tiny! It is sweet! You turn small and when u mount ur mount turns small. I've heard from a friend that when u ride a griffin it turns small. 
(#1 happens a lot to me and #2 and #3 happen little.)"
