### ISSUE TITLE
Hexenmeister: Wichtel 

### ISSUE THREAD

**Issue by LPnertz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#664]
Der Wichtel des hexxenmeisters geht nicht mehr in den nahkampf und greift nur mit seinen zaubern an  ansonsten steht er nur doof rum im Kampf wenn man die zauber nicht aktiviert

**Comment by hraesvelgr** [comment]
A common mistake some warlocks make is to tell their Imp to attack when Firebolt isn't set to auto-cast. Since Firebolt is the Imp's only attack form, this gives it nothing to do; right-click on the Firebolt button to fix it. An Imp will also not attack if it is out of mana; it will also refuse to attack mobs that are immune to fire. 

http://www.wowwiki.com/Imp_(warlock_minion)#Imp_tips

absolut blizzlike bei uns.

**Comment by Larnak1** [comment]
Jop, der Nahkampf war ein Bug.
