### ISSUE TITLE
Jäger: Schusswaffen

### ISSUE THREAD

**Issue by zutrer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#680]
Thoriumgewehr lvl47: Schaden 42-79 tempo 2.50 dps 24.2 und +17 distanzangrifskraft
Kugelspeiende Schrotflinte lvl53 (blau item): Schaden 48-89 tempo 2.30 dps 30.9 + 1-4 Feuerschaden

Habe mal alle Rüstungen und Items ausgezogen und bin in den Kampf gegen die Wasserelementare im Arathihochland (lvl38-39). Bin Jäger lvl53.
Im Charakterbaum wird das Thorimgewehr mit Schaden 147-186 und dps 75.3 angezeigt.
die Schrotflinte mit 93-97 Schaden und dps 46.6.
Im Test gegen die Wasserelementare bestätigen sich diese werte, die Schrotflinte ist massif schwächer als das sie sein müste.
erst mit "Aspekt des Falken" + 90 Distanzangriffskraft und "Aura des Volltreffers" +45 Angriffskraft und "Mal des Jägers" +79 Distanzangriffskraft kann es die Schrotflinte mit dem Thoriumgewehr (ohne buffs) aufnehmen.

wieso ist mein selbstgebautes Thoriumgewehr besser als als die blaue lvl53 Schrottflinte

update mit Aspekt und Aura zeigt es im Charakterfenster für die Schrotflinte 121-125 Schaden und 60.6 dps

**Comment by Rushor** [comment]
was buggt denn rum?

**Comment by dagochen** [comment]
Das Problem ist das Waffen mit +Elementarschaden nicht korrekt funktionieren. Wurde schon 100x reported, daher ein Doppelpost --> Closed

**Comment by Haudraufinix** [comment]
*- Ranged Elemental Damage: Our ranged combat system does not allow a
ranged weapon to do a mix of Elemental (Fire, Frost, Arcane, etc.)
and Physical damage. Many ranged weapons existed which were listed
as doing Elemental damage and did not function properly (the damage
was dealt, but was treated as Physical). All of those weapons have
been changed to deliver the Elemental damage as a chance on hit
effect. Hurricane was previously changed this way in 1.11. The
following ranged weapons are also fixed in 1.12: Bow of Searing
Arrows, Dwarven Hand Cannon, Heartseeking Crossbow, Dark Iron Rifle,
Galgann's Fireblaster, Quillshooter, Shell Launcher Shotgun,
Venomstrike, and Verdant Keeper's Aim.*

Aus http://forums.mammae.eu/index.php?threads/patch-1-12-notes.1994/

Also sind alle Elementar Range waffen auf nem falschen Patchstand und das Problem nach einem Datenbankupdate quasi hinfällig. Eine verschenkte chance für Spelldmgjäger, aber wenigstens müssten die Proccs der Waffen n scaling haben :D

**Comment by dagochen** [comment]
Dwarven Hand Cannon: http://datenbank.welli-it.de/?spell=29647 und http://datenbank.welli-it.de/?spell=29635

Bow of Searing Arrows: http://datenbank.welli-it.de/?spell=29638 und http://datenbank.welli-it.de/?spell=29624

Dark Iron Rifle: http://datenbank.welli-it.de/?spell=29632 und http://datenbank.welli-it.de/?spell=29641

Galgann's Fireblaster: http://datenbank.welli-it.de/?spell=29633 und http://datenbank.welli-it.de/?spell=29644

Quillshooter: http://datenbank.welli-it.de/?spell=29634 und http://datenbank.welli-it.de/?spell=29646

Shell Launcher Shotgun: http://datenbank.welli-it.de/?spell=29635 und http://datenbank.welli-it.de/?spell=29647

Venomstrike: http://datenbank.welli-it.de/?spell=29636 und http://datenbank.welli-it.de/?spell=29653

Verdant Keeper's Aim: http://datenbank.welli-it.de/?spell=29637 und http://datenbank.welli-it.de/?spell=29655

Dark Iron Rilfe: http://datenbank.welli-it.de/?spell=29626 und http://datenbank.welli-it.de/?spell=29640

**Comment by wahaxlekuke** [comment]
Möglicherweise müsst ihr noch den WDB-Ordner löschen, weil sonst der Tooltip falsch angezeigt wird.
