### ISSUE TITLE
Waffenwertung

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#813]
Waffenwertung gibt bereits ab 310 Waffenwertung 100% Glancingschaden, statt ab 315 Waffenwertung. Dadurch machen Nahkämpfer im PvE geringfügig zu viel Schaden.

siehe: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/17
wo Nightblizzard selber erwähnt, dass irgendwas nicht stimmen kann.

siehe: http://community.mmobase.de/talk-und-allgemeines/6947-waffenwertung-skaliert-zu-hoch.html
wo über diese Thematik diskutiert wurde.

Im ersten Schritt sollte diese Formel eingeführt werden:
Reduction = 5*(2^(MobLvL-Weaponskill/5)-1)
und dazu braucht man noch eine andere Formel die den Glancingschaden ab 315 über 100% Waffenschaden hebt. 
Dafür sind meine Matheskills nicht gut genug. Vielleicht reicht diese Formel aber auch dafür.

**Comment by Seniorash** [comment]
Wenn man über das Cap kommt sollten die Glancings 100% nicht überschreiten und weiterhin nicht kritisch treffen können. 
Ich halte die hier angegebene Formel für korrekt, weil sie mit den gemessenen Stützpunkten aus den Foren und dem Wiki-Eintrag übereinstimmt.

**Comment by Testear** [comment]
Wenn diese Formel richtig ist, dann muss ab >315 Waffenwertung etwas anderes passieren. 
Was nebenbei eh theoretisch ist, da kein Melee mit Verstand über 310 hinausgeht.

**Comment by Seniorash** [comment]
Die Formel ist einfach Curvefitting an die gemessenen Werte

**Comment by Testear** [comment]
kannst du auch noch was konstruktives schreiben? ich denke nicht, also halte doch einfach die finger bei dir

**Comment by Gromnir** [comment]
Schwieriges Thema. Habe mir auch lange die Zähne dran ausgebissen und die Tests damals für den Fix gemacht. 
http://community.mmobase.de/sonstige-fehler/4899-glancing-blows-streifschlaege-funktionieren-nicht-richtig.html

Leider kann man nichts 100%tiges finden. Dhorn hat hierzu auch mal was schönes zusammengefasst was ich hier posten möchte, was eher für ein 310 Cap spricht:
http://pastebin.com/wws7FZyS
Er arguemntiert hierbei gegen die Wiki Formel von hier: 
http://wowwiki.wikia.com/Weapon_skill?oldid=349298
(30. November)

Auch muss man bei dem Autor des geänderten Wiki-Artikels vom 30. November 2006 sagen, dass dieser scheinbar damals negativ aufgefallen ist, da er mehrere Artikeleinträge geändert hat:
http://wow.gamepedia.com/Talk:Dodge
"Beaza changed values I personally verified with awkward values, and directly contradicted various blue statements from forums over the past two years (among others), including things that can be observed like : each point of Defense increases Block, Parry, Dodge, and Miss chance against you by 0.04% (Beaza says 0.01%), or that WoW combat is table-based (Beaza says it's an if-then-else system).
Beaza, who has no contribution before today (no Wowwiki history) has modified today (or is MODIFYING right now) every combat-related article to show his/her view. I consider this vandalism, as he/she does not back ANY CHANGE in the Discussions but merely inputs data which may be, as far as I know, arbitrary and/or incorrect."

Der Wiki Artikel vor seiner Bearbeitung nutzt auch die Damage Formel für das 310 Skill Cap:
http://wowwiki.wikia.com/Weapon_skill?oldid=326000
15. November

Mein Verständnis ist, dass damals generell die Meinung vertreten war, dass das Cap bei 310 lag. Die meisten Guides oder Forenbeiträge weisen auf diese Zahl hin. Aber da es damals keine guten Testumgebungen gab, muss das natürlich nicht stimmen (hierzu Zähl ich auch die Zahlen aus dem Wiki Artikel von dem User Athan). Ich persönlich würde es bei der jetztigen Formel belassen...man kann sich aber über eine Änderung wohl auch nicht beklagen.

**Comment by Sabbaer** [comment]
gehen wir aufm server nicht nach wowwiki? ist doch die bibel und unantastbar? sonst zweifel ich auch einiges anderes an, was da geschrieben steht?

**Comment by Seniorash** [comment]
http://wowwiki.wikia.com/Talk:Weapon_skill
Dort wurde das mit einer Anzahl von mehreren tausend Hits getestet. Da die Procchance sehr genau ermittelt wurde, kann auch angenommen werden dass die Reduction ebenfalls richtig ist. Mein Spreadsheet geht ebenfalls von einem Cap von 315 aus, wobei bis 310 Waffenkunde 30% DMG-Reduction ausgeglichen werden und die letzten 5 nur noch 5% DMG-Reduction ausgleichen (wodurch das allgemeine Verständnis von einem Cap von 310 Waffenwertung kommt). 

Hier einmal noch ein Teil aus meinem MMO-Post zum Vergleich der DMG-Reduction auf unserem Server und den gemessenen Werten im Forum.
Glancings Damage Reduce:

Auf unserem Server:
Lvl 60 Puppe / 300 Weaponskill -> 0% Damage reduce :+1:
Lvl 61 Puppe / 300 Weaponskill -> 0% Damage reduce :+1:
Lvl 62 Puppe / 300 Weaponskill -> ~15% Damage reduce 
Lvl 63 Puppe / 300 Weaponskill -> 30% Damage reduce :+1: 

Aus dem Forum mit 300 Waffenskill:
61 Mobs: 3,3% DMG Reduction
62 Mobs: 14,2% DMG Reduction
63 Mobs: 34,3% DMG Reduction


Auf unserem Server Reduce bei Bossen:
Lvl 63 Puppe / 300 Weaponskill -> 30% Damage reduce :+1: 
Lvl 63 Puppe / 305 Weaponskill -> 15% Damage reduce :+1:
Lvl 63 Puppe / 310 Weaponskill -> 0% Damage reduce :+1:

Laut den Berechnungen aus dem Forum:
Lvl 63 Puppe / 300 Weaponskill -> 35% Damage reduce 
Lvl 63 Puppe / 305 Weaponskill -> 15% Damage reduce
Lvl 63 Puppe / 310 Weaponskill -> 5% Damage reduce 
Lvl 63 Puppe / 315 Weaponskill -> 0% Damage reduce 

Die angegebene Formel aus dem Bugreport stimmt hingegen 100% mit den gegebenen Stützpunkten überein.
Was bei uns vor allem merkwürdig ist, dass es keine DMG-Reduction bei lvl 61er Mobs gibt (es sind sich aber alle einig dass die Glancingchance 10% betragen muss, was allerdings gar keinen Effekt hat).

**Comment by Hakii** [comment]
Glancing blows
Against mobs that are of equal level or higher, you will have a chance to land a glancing blow instead of a normal hit. A glancing blow only occurs on white melee damage, cannot crit, and has a damage reduction proportional to the difference between the attacker's weapon skill and the target's defense. Weapon skill above your level * 5, as from gear or racial bonuses, reduces the severity of the damage reduction, but not your chance to land a glancing blow.

[edit]Glancing Blow chance
The percentage chance of a glancing blow on any melee auto-attack, with either the main hand weapon or the off-hand weapon, is normally agreed to be the following:

(NPC’s Defense skill – YOUR Weapon skill – 5) * 3% + 10%
... where "YOUR Weapon skill" is capped at your level * 5.

The assumption is that the NPC's Defense skill is always equal to its level * 5. However, Glancing Blows have been seen with a level 60 character, 300 weapon skill, against mobs 1 or more levels higher. Glancing Blows have even been seen against mobs of the same level as the attacker. Either the above formula is incorrect, or some mobs have a Defense value that is higher than their level * 5. (Again, see Talk page).

This formula means that, for a level 60 player with fully trained weapon skill, 25% of all white-damage melee attacks will be Glancing Blows against level 62 mobs, and 40% of all white-damage melee attacks will be Glancing Blows against level 63 mobs.

The presence of your weapon skill in this formula, rather than just your level, explains why training up a newly-acquired weapon skill against mobs close to your own level results in many, many Glancing Blows at first.

[edit]Glancing Blow damage reduction
The damage reduction is:

(Target’s Defense skill – Your Weapon skill - 5) * 3%.
This gives a level 60 player, with fully trained but otherwise unbuffed weapon skill, a 15% damage reduction with all Glancing Blows against level 62 mobs, and a 30% damage reduction with all Glancing Blows against level 63 mobs.

Unlike the chances of getting a glancing blow, the player's weapon skill is not capped at level * 5 in the damage reduction formula. With +5 weapon skill, a level 60 player attacking a level 63 NPC will see the same amount of glancing blows (40%), but only 15% damage reduction. With +10 weapon skill, the damage reduction becomes negligible.

[edit]Glancing Blow Implications
With + to weapon skill you will have the exact same percentage of glancing blows, but each glancing blow will land harder. With enough + to weapon skill, all your glancing blows will hit just as hard as your normal, non-glancing blows.

The fact that 40% of all white-damage melee attacks made against a Boss Mob will be Glancing Blows, no matter what you do, has serious implications when choosing how much +crit% gear to use. Due to the table-based nature of WoW's attack resolution system, Glancing Blows take precedence over critical hits. If your combined miss, dodge, parry, block, glancing blow, and crit chance against a mob is 100% or higher, you will never see a normal white-damage hit made against that mob (all your hits will be either glancing blows or critical hits). If it exceeds 100%, it is your critical hit chance that gets "pushed off the end" of the table. Any +crit% gear added past this point will not improve your critical hit chance with white-damage melee attacks at all. This is sometimes called the "Crit cap" (see below).

Instant attacks, and "yellow damage" on-next-swing attacks such as Heroic Strike, do not produce Glancing Blows. For these attacks, added +crit% gear beyond the "Crit cap" described above will improve your critical hit chance.

Ranged weapon attacks (Bows, guns and crossbows) do not have glancing blows at all, thus weapon skill does not affect this for them. It works the same for all classes that can use ranged weapons (hunters, rogues and warriors).


Quelle (http://wowwiki.wikia.com/wiki/Formulas:Weapon_Skill#Glancing_blows)

 
Das ist der original WoWWiki Eintrag mit Zeitstempel nicht älter als 26.09.2006. Der Forenpost wurde direkt mit der Weapon Skill Seite von WoWWiki verlinkt. Der Linkt funktioniert noch, führt aber auf die aktualisierte Seite. (Forenpost von nicole@blackhand 26. September 2006, 12:10)

**Comment by Testear** [comment]
Hast du mal Zahlen in deine Formeln eingegeben? 

The percentage chance of a glancing blow on any melee auto-attack, with either the main hand weapon or the off-hand weapon, is normally agreed to be the following:

(NPC’s Defense skill – YOUR Weapon skill – 5) * 3% + 10%
... where "YOUR Weapon skill" is capped at your level * 5.

mit 315 Bossdef und 310 Spielerwk ergibt 0,1 % Glancingblowchance - Interessant. Wir haben haufenweise Quellen die Belegen, dass die Chance auf Glancing Blows nicht verringert werden kann.

 (Target’s Defense skill – Your Weapon skill - 5) * 3%.
This gives a level 60 player, with fully trained but otherwise unbuffed weapon skill, a 15% damage reduction with all Glancing Blows against level 62 mobs, and a 30% damage reduction with all Glancing Blows against level 63 mobs.

Mit 315 Bossdef und 310 Waffenkunde ergibt diese Formen eine Dmgreduzierung um 0% - Es sollten 5% sein. Wie die Diskussion im Mmobse Forum ergeben hat.

**Comment by Hakii** [comment]
Nachdem ich mir http://wowwiki.wikia.com/wiki/Weapon_skill?oldid=349298 angeschaut habe, muss ich den 5% zustimmen. :-)

**Comment by Seniorash** [comment]
Die tatsächliche Formel ist/war keinem Spieler 100 %ig bekannt. Aber bei den DMG-Reduction Werten ist klar, dass es sich nicht um eine lineare Gleichung handeln kann. Deswegen bitte erst alle gesammelten Infos durchlesen bevor sowas gepostet wird bitte.
Und auch beim Thema bleiben. Um die Glancingrate geht es hier überhaupt nicht. Einfach den Wiki-Eintrag hier rein zu kopieren müllt nur den Report zu.

**Comment by Hakii** [comment]
Such dir einfach die Überschrift "Glancing Blow damage reduction" aus dem Link raus...

**Comment by Seniorash** [comment]
Welchen Sinn soll dann eine 10% glancing rate gegen 61er haben wenn die DMG-Reduction dabei 0 ist?
Außerdem wird auch in deinen Quellen gesagt dass die DMG-Reduction bei 10 Waffenkunde vernachlässigbar ist. Vernachlässigbar ist aber nicht gleich 0 wie auf unserem Server. 
Laut meinem Spreadsheet sind die 5% ebenfalls korrekt.

**Comment by Hakii** [comment]
Zu allen Theorien dieses Themas gibt es einfach keine nachvollziehbaren Auswertungen/Belege aus jener Zeit. 

Der Post aus dem Talkbereich von WoWWiki....

Core Hound (61 elite):
Glancing (Hits)                    20.48% of 2798 swings
Average Glancing           Damage: 148
Average Hit                Damage: 153
Average Crit               Damage: 322
Average Hits + Half Crits  Damage: 157
Glancing Dmg/Average Hit   Damage: 0.969
Glancing Dmg/Avg Hit+Crit  Damage: 0.944

Molten Giant (62 elite):
Glancing (Hits)                    30.85% of 8834 swings
Average Glancing           Damage: 151
Average Hit                Damage: 176
Average Crit               Damage: 362
Average Hits + Half Crits  Damage: 178
Glancing Dmg/Average Hit   Damage: 0.856
Glancing Dmg/Avg Hit+Crit  Damage: 0.844

Molten Destroyer (63 elite):
Glancing (Hits)                    41.58% of 4938 swings
Average Glancing           Damage: 118
Average Hit                Damage: 180
Average Crit               Damage: 376
Average Hits + Half Crits  Damage: 184
Glancing Dmg/Average Hit   Damage: 0.656
Glancing Dmg/Avg Hit+Crit  Damage: 0.642

... vergleicht einfach den durchschnittlichen Hit mit dem durchschnittlichen Glancing. ABER! 

Average Glancing           Damage: 148
Average Hit                Damage: 153

Die Waffe verfügt über eine Attackrange, es kann durchaus möglich sein, dass die Rolls für den Glancing-Schaden zufällig im Schnitt 5 niedriger waren.

Als kontrastbeispiel habe ich in den letzten Tagen 1500 Whitehits mit 305 Waffenrating auf LvL62 Ziele ausgeübt. Zwar sind 1500 noch nicht viel, aber in meinem Kampflog betrug der Unterschied zwischen Hit und Glance 0% (siehe Vergleichsmöglichkeiten im Vorpost). Im Durchschnitt haben meine Glancings aber 2% mehr Schaden gemacht, als meine Hits. Einfach deshalb, weil für meine Glancings höhere Rolls stattgefunden haben.

**Comment by Seniorash** [comment]
Mit 305 Waffenrating hast du bei uns auf 61er und 62er eine DMG-Reduction von 0%. Daher hat der Test keinen Aussagewert, da du nach 1500 Hits immer eine gewisse Schwankung haben wirst die du auch festgestellt hast . Dass aus dem Mittelwerten der Glancings und Hits die DMG-Reduction nicht abgeleitet werden kann, kann ich nicht nachvollziehen. 
Klar ist es hierbei schwierig zuverlässige Aussagen zu finden. Alle verfügbaren Quellen deuten jedoch auf 5% bei 61er Mobs bei 0 Waffenwertung hin. Bei dem Post aus dem Wiki-Forum stimmen außerdem auch die anderen Werte mit allen anderen genannten Quellen aus dem MMO-Forum überein (insbesondere gegen 63er Mobs bzw. Bosse). Solange es keine andere Quelle angibt wie "vernachlässigbar" die Waffenwertung über 310 ist, ist davon auszugehen dass die hier ermittelten 5% korrekt sind.

**Comment by Hakii** [comment]
"Dass aus dem Mittelwerten der Glancings und Hits die DMG-Reduction nicht abgeleitet werden kann, kann ich nicht nachvollziehen."

Deine Angriffe haben ja eine Attack-Range. Meine Mainhand hat beispielsweise eine Schadensrange zwischen schwächstem Hit und stärkstem Hit von 65 (195-260). Ein Glancing hat in diesem Fall eine Schadenrange von 185-247 (195-260 jewils abzüglich 5%). In dem Schadensbereich 195-247 treten sowohl Glancings als auch Hits auf. Somit kanne es durchaus möglich sein, dass der Durchschnittsschaden von Glancings höher sein kann, als die der normalen Hits und zwar genau dann, wenn sich die Hits auf einem niedrigeren Niveau in der Attackrange befinden, als die Glancings.

Ich habe mit meinen 305 Waffenrating auch Tests an LvL 61 Ziele absolviert (2000 Hits). Hier ist der tatsächliche Unterschied zwischen Hit und Glancing auch 0%, dennoch waren meine Glancings im Schnitt 1% schwächer, als meine Hits.

"Solange es keine andere Quelle angibt wie "vernachlässigbar" die Waffenwertung über 310 ist, ist davon auszugehen dass die hier ermittelten 5% korrekt sind."

Es gibt keinerlei Hinweise, wie man auf diese Rechnungen gekommen ist. Keinen Changelog-Eintrag in der Historie, keine(n) Link(s), kein Eintrag im Talkbereich. Der Eintrag wurde exakt 5 Tage vor 2.0.1 veröffentlicht, was auch wenig Sinn macht, da es ab 2.0.1 eh keine Rolle mehr gespielt hat.

**Comment by Testear** [comment]
1. Da du sagst es gibt keinen Hinweis wie man auf die Formel gekommen ist weise ich dich daraufhin, dass du dich nicht durch alle im Mmobse Forum verlinkten Quellen gelesen hast.


2. Natürlich kann man über den Durchschnittsschaden die Differenz zwischen Glancings und normalen Autohits vergleichen. Auch, wenn die Glancings mal mehr Schaden machen als die Autohits.
Denn Glancings sind keine normalen Hits und werden dementsprechend anders geloggt. Es ist um die Dmgreduktion zu errechnen völlig ausreichend die Durchschnittswerte zu wissen - ganz einfach weil die Anzahl der Glancings immer 40% entspricht. 


"Ich habe mit meinen 305 Waffenrating auch Tests an LvL 61 Ziele absolviert (2000 Hits). Hier ist der tatsächliche Unterschied zwischen Hit und Glancing auch 0%, dennoch waren meine Glancings im Schnitt 1% schwächer, als meine Hits."

Was auch genauso sein sollte. Aber aktuell solltest du mit 300 Waffenwertung auf exakt das gleiche Ergebnis kommen. 
Hattest wohl einfach Pech mit deinen Glancings, dass sie nicht genauso viel Dmg wie deine Autohits gemacht haben.

3. Du behauptest einfach ohne zu wissen. Hör auf damit.

**Comment by Sabbaer** [comment]
push
