### ISSUE TITLE
Knochenhäschers Schneide

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#967]
Der Procc von Knochenhäschers Schneide ist ein Buff sollte aber ein Debuff auf dem gegnerischen Ziel sein.

http://wowwiki.wikia.com/wiki/Bonereaver%27s_Edge

Der Buff wurde erst mit 3.0.2 eingeführt wie man im oben aufgeführten Link sehen kann.

**Comment by Gromnir** [comment]
Falsch, schau dir den Wiki Eintrag von 2006 an:
http://wowwiki.wikia.com/wiki/Bonereaver%27s_Edge?oldid=289415
"Since a recent patch, the proc effect is a buff on the player wielding the sword and therefore stacks with the sunder armor debuff. "

https://www.youtube.com/watch?v=EX8N51wStMk
5:44 Ists au ein Buff. 

https://www.youtube.com/watch?v=dd90O5LkikY
3:43 Rechts die Buffleiste


Über was man vllt (In nem neuen Thread) diskutieren kann wär die proc chance, die wirkt zu niedrig :)

**Comment by Archidamos** [comment]
Zu niedrig? Im Ernst?

**Comment by ChichiWarrior** [comment]
Die Proc-Chance wurde ausgiebig getestet und ist jetzt richtig.

Gab dafür schon einen Report.

Gruß

Chichi

**Comment by Testear** [comment]
Ein Video von 2011 und eines von 2012. 
Und eine Quelle die von einem "zurückliegendem Patch" spricht. Gehts auch genauer?

**Comment by hraesvelgr** [comment]
wenn bei wowwiki eindeutig aufgeführt wird, mit datum und patch-stand, dass es von einem debuff zu einem buff geändert wurde, warum zweifeln dann leute an so einer information? 


das kam mit patch 1.10.0
>The  Bonereaver's Edge's triggered effect has been changed. Instead of lowering your victim's armor, it will cause you to ignore a portion of your victim's armor. Its triggering rate was substantially increased as well as the magnitude of the effect. In addition, the item now has 16 stamina.

ich denke mal das meint dein beitrag von 2006 mit "since a recent patch", @Gromnir 

jetz is nur die frage, wie man bei einem debuff umsetzt, dass nur ein einzelner spieler (und kein anderer) 700 armor des gedebufften ziels ignoriert.

**Comment by Gromnir** [comment]
Klassik videos, die 2011 und 2012 hochgeladen wurden weils google video nimmer gibt^^
http://www.warcraftmovies.com/movieview.php?id=32669

Aber ja, hier der "Recent Patch" 1.10
"The Bonereaver's Edge's triggered effect has been changed. Instead of lowering your victim's armor, it will cause you to ignore a portion of your victim's armor. Its triggering rate was substantially increased as well as the magnitude of the effect. In addition, the item now has 16 stamina"
http://wowwiki.wikia.com/wiki/Patch_1.10.0

Die Proc-Rate der Waffe sollte nach dem Patch bei ca. 17%-20% liegen (wirkt auf mich hier zu niedrig, keine Ahnung wie hoch es bei uns eingestellt ist. Keine Puppen zum testen). Die Waffe war auch schon damals underrated und gleichzusetzen mit Ashkandi. Was aber unterschiedlich zu den damaligen Classic-Server und unserem ist, dass BRE viel seltener gedroppt ist, weil der Ragnaros Loottable bei uns falsch ist (Falsche Dropraten wie bei Neferian als der hier rauskam). Tendenziell haben Waffen bei Endbossen meines Wissens nach immer ne viel geringere Chance zu Droppen als der restliche Loot. Hier kann BRE theoretisch 3x bei Raggi Droppen (8%, 8%, 3%) wenn ich die Datenbank richtig lese, was so nicht richtig ist. Deshalb läuft auch fast jeder mit BRE oder der Axt herum. Blizzlike, wäre es, wenn die lootgruppe mit BRE, der Axt und dem Shard (laut Atlas) nur eine einmalige Chance zum Droppen hätte und diese nicht bei 100% liegt. (so, nebenbei ;D )

**Comment by Testear** [comment]
Das purgen/ dispellen ist nicht das Problem, weil der Buff als Fluch gewertet wird.
Soweit ich weiss liegt die Proccrate hier bei ca 16%, aber das ist nicht Thema dieses Reports.

**Comment by dagochen** [comment]
Fazit: Kein Buff, sondern ein Debuff und auf dem Spieler, der die Waffe nutzt, nicht auf dem Ziel. Korrekt soweit?

PS: Chance ist auf Nefarian bei 17 oder 18%, wenn ich mich nicht irre und nicht mehr dran rumgeschraubt wurde. Gibt doch bestimmt nen Addon, dass die Chance bestätigen kann und mitzählt?Alternative: Duell machen und selbst mitzählen?

**Comment by Gromnir** [comment]
Nein, das ist nicht ganz richtig.

- Der Proc löst einen Buff aus. 
Siehe dazu auch die Videos die ich gepostet habe. Das eine ist bei warcraftmovies von 2006 und der Autor erwähnt in der Beschreibung, er wollte das Video vor dem BC patch rausbringen (Sollte auf genau unserem Patchstand sein, auch wenns im Dezember hochgeladen wurde). 
Das andere Video zeigt ab 7:34 die Klassik-Skillbäume. Also, auch wenn die Videos bei youtube erst später hochgeladen worden sind, sinds beide Klassik Videos die nicht auf nem Privatserver aufgenommen wurden.
- Der Buff von BRE ist gleichzeitig ein Fluch bzw. als Fluch klassifiziert
- Der Buff/Fluch ignoriert einen Teil der Rüstung des Gegners.
- Weil das Ding gleichzeitig ein Fluch ist, wird es nicht mehr vom Grounding Totem gefressen, da dieser wohl als Eigenschaft vor dem Patch 1.10 hatte, alle Flüche auf einem Char umzulenken (das ist aber nur ne Vermutung meinerseits, würde mMn aber Sinn machen^^)
- Befreundete Druiden können den Buff nicht entfernen, obowhl es ein Fluch ist.

- Wo ich mir nicht sicher bin, ist ob feindliche Priester den Effekt entfernen können, weil es ein Fluch ist.

**Comment by Seniorash** [comment]
Ist ein Buff: https://www.youtube.com/watch?v=3wHxtDGQs_U bei 1:19

**Comment by Testear** [comment]
Okay. Dann können wir ja hier schließen.
