### ISSUE TITLE
Thunderfury Proccrate zu niedrig

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#977]
Ich hatte bei 500 Treffern mit Thunderfury 58 Proccs. 

Laut http://wowwiki.wikia.com/wiki/Thunderfury,_Blessed_Blade_of_the_Windseeker?direction=prev&oldid=351349
sollte ich mindestens 100 Proccs haben.
Ich denke der Mittelwert 22,5% wäre in Ordnung.

The proc effect has been observed to be approximately 20-25%

**Comment by dagochen** [comment]
Ich vermute mal das du bei den 500 Hits keine Styles verwendet hast, diese können TF auch proccen lassen. Wenn du von ca 1 Style pro Auto-Attack ausgehst, verdoppelst du damit die Anzahl an Procs und bist bei 116/500 = 23,2% in deinem Fall.

**Comment by Testear** [comment]
Ich vermute mal..... heißt du hast keine Ahnung. 

Nein ich habe auch Styles verwendet. 

Nebenbei. Hätte ich nur Autohits verwendet wäre ich zum selben Ergebnis gekommen, weil 500 Treffer 500 Treffer bleiben.

**Comment by dagochen** [comment]
Ich war davon ausgegangen, dass die  20-25% anteilmäßig an den Whitehits berechnet wurde. Dann reichen ca. 12% Procchance aus, um durch Styles auf diese Prozentwerte zu kommen, was wiederum geheißen hätte, dass du ohne Styles bei 58/500 genau im soll liegst. 

Aber ich hab grad nochmal nachgelesen, die Chance soll 25% auf Whitehits und auf Special Abilities sein. Wenn ich mit meiner Annahme oben, wie es hier auf Nefarian vermutlich ist, Recht habe, muss was geändert werden, ansonsten hast du nur Pech gehabt :)

**Comment by Sabbaer** [comment]
ist das bei anderen waffen auch der fall, z.B. dem raggi hammer?

**Comment by Seniorash** [comment]
Ich habe 60.000 Autohits gemacht und da war die Quote etwa 11,5% (auf aller erfolgreichen Treffer bozogen)

**Comment by Hakii** [comment]
Mit 1.9 wurde die Proccchance von Thunderfury generfed. In den Patchnotes steht zwar nicht auf welchen Wert, in den üblichen Diskussionsforen wurden Werte zwischen 15-18% ermittelt, in den meisten Spreadsheets wurde mit einem Wert von 17% gearbeitet. Selbstredend können nur die von Thunderfury ausgeführten Schläge den Effekt proccen.

http://wowwiki.wikia.com/wiki/Patch_1.9.0

**Comment by Testear** [comment]
Das ist korrekt, aber sie wurde dannach wieder verbessert.

**Comment by Seniorash** [comment]
http://forum.nostalrius.org/viewtopic.php?f=24&t=703
Dort wurde dieses Thema recht ausgiebig recherchiert. Hier mal die TLDR Version, die sich auch auf anderen Seiten wiederfindet:
Original 1.6 Version: 30% Proc Chance with ability to Proc from itself and any other damage from weapon (poisons, trinkets, enchants etc)
Nerfed 1.9 Version: 15% Proc Chance only from auto attacks and special abilities.
Restored 1.12 Version: 25% Proc Chance from auto attacks and special abilities. 

Dort sind auch Ergebnisse von einigen Tests die diese Procchance bestätigen.
Patch 1.12
August 31 – Cites changes in proc rate from 5.2 hits per proc(19%) to 4.3 (23%) (2700 attack iteration) 
Q: “Prior to 1.12, Procwatch was giving me a TF "hits per proc" of around 5.2. Currently, with something like 2700 attacks, it's giving me a "hits per proc" of 4.3. Anyone else seeing an increase in proc rate? Or have I just been either lucky since the patch, or unlucky previous to it.

**Comment by Seniorash** [comment]
Gibt es zu diesem Thema noch eine Rückmeldung?
Es gibt zahlreiche Quellen, die belegen dass die Procchance nach dem Nerf in 1.9 wieder erhöht wurde. Hier eine weitere: 
Up until 2.0 patch on live I was running proc watch on my TF, and it came out pretty consistently over the 4 or 5 times I reset it to a 25% proc rate. This was with sample sizes of 20,000+ swings.
http://forums.elitistjerks.com/topic/9347-new-beta-patch-notes-203/page-4#entry259489

Die aktuelle Procchance von etwa 11% orientiert sich hingegen wahrscheinlich an dem Patchstand 1.9.

**Comment by ErnisKommentar** [comment]
@Testear 

Daran müssen Sie sich hier gewöhnen, dass Personen, die keine Ahnung haben Sie zutexten unter Beifall der ebenfalls ahnungslosen Betreiber des Servers. Ist leider so. Das ist in der Tat "blizzardlike".

**Comment by dagochen** [comment]
Los Ernie! Bastel uns die Korrektur!
